---
- name: Add systemd unit
  template:
    src: bot.service.j2
    dest: /etc/systemd/system/bot.service

- name: Make folder for bot
  file:
    state: directory
    path: "{{ bot_folder_path }}"
    owner: bot
    mode: 0755

- name: Copy bot script
  template:
    src: bot.py.j2
    dest: "{{ (bot_folder_path, bot_file_name) | path_join }}"
  notify:
    - restart bot

- name: Copy bot requirements
  template:
    src: requirements.txt
    dest: "{{ (bot_folder_path, 'requirements.txt',) | path_join }}"

- name: Install bot requirements
  pip:
    requirements: "{{ (bot_folder_path, 'requirements.txt',) | path_join }}"
  notify:
    - restart bot

- name: Enable and start Bot
  systemd:
    daemon_reload: yes
    name: bot
    enabled: yes
    state: started
  ignore_errors: "{{ ansible_check_mode }}"